cargo-features = ["edition2024"]

[package]
name = "proc"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.64", features = ["full"] }
quote = "1.0.36"

[lib]
proc-macro = true